name: Fire-Away

views:

  - name: ''
    class: CNCView
    menu: Fire-Away
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: Fire-Away
      description: >
        Use this tool to upload links, files or hashes to WF for analysis
      documentation_link: http://github.com/mitch-pan/fire-away
      next: run_uploader


# Options grouped by architecture
  - name: run_uploader
    class: uploadView
    menu: Fire-Away
    menu_option: Fire Away!
    attributes:
      header: Fire-Away
      title: WildFire Results
      help_text: |
        File Name - Name of file to upload to WF

  - name: provision
    class: ProvisionSnippetView



