name: Fire-Away

views:

  - name: ''
    class: CNCView
    menu: Fire-Away
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: Fire-Away
      description: >
        Use this tool to upload links, files or hashes to WF for analysis
      documentation_link: http://github.com/mitch-pan/fire-away
      next: run_uploader


# Options grouped by architecture
  - name: run_uploader
    class: uploadView
    menu: Fire-Away
    menu_option: Fire Away!
    attributes:
      header: WildFire query option
      help_text: |
        API KEY - The WF API key for your account
        URL - A URL to submit to WildFire for analysis
        File Name - Name of file to upload to WF
        SHA256 - A hash of a link or file to send to WildFire for a verdict

  - name: provision
    class: ProvisionSnippetView



