name: wfUploader

views:

  - name: ''
    class: CNCView
    menu: WF Uploader
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: WildFire Uploader
      description: >
        Use this tool to upload files or hashes to WF for analysis
      documentation_link: http://github.com/mitch-pan/wf-uploader
      next: run_uploader


# Options grouped by architecture
  - name: run_uploader
    class: uploadView
    menu: WF Uploader
    menu_option: Run Uploader
    attributes:
      header: Uploader
      title: WildFire Results
      help_text: |
        File Name - Name of file to upload to WF
        API Key - A valid WF API Key
 
  - name: provision
    class: ProvisionSnippetView



