name: run_uploader
label: Run the Fire-Away application
description: Runs Fire-Away Query
type: app
extends:

labels:
  service_type: tort_assess

variables:
- name: api_key
  description: WildFire API Key
  default: 
  type_hint: text
- name: link
  description: URL to submit to WF
  default:
  type_hint: text
- name: file_name
  description: Path of file to upload
  default: Full Path To File
  type_hint: text
- name: hash
  description: SHA256 of the file or link to query (optional)
  default:
  type_hint: text

snippets:
